### ISSUE TITLE
CSS in JS Syntax highlighting comes and goes as you exit CSS region

### ISSUE THREAD

**Issue by stevemolitor** [orzechowskid/tsx-mode.el#10]
Not sure if this is a bug or working as designed. When you enter a CSS in JS region it gets syntax highlighted, and when the cursor leaves the region it's highlighting as a regular string again:

![](https://cdn.zappy.app/5a08baadc6347d22385d18947d6b624b.gif)

**Comment by orzechowskid** [comment]
that was intentional, the justification being I care about CSS syntax highlighting when I'm editing that CSS but don't care about it if I'm editing a different part of the file.

I can make that configurable if you find it too distracting but it might take a bit of effort.

**Comment by stevemolitor** [comment]
Is there a performance cost?

I’d prefer to have the syntax highlighting always on because it helps me read the CSS even when not editing it.

**Comment by orzechowskid** [comment]
I don't think there will be any performance concerns.  I just have to apply CSS highlighting to CSS-in-JS strings when the major mode is first enabled, and then be sure not to apply `font-lock-string-face` to CSS-in-JS strings when point moves out of them.  shouldn't be too hard, it's just not a 1- or 2-line fix.

**Comment by orzechowskid** [comment]
I've just added a new `defcustom` named `tsx-mode-css-force-highlighting` which when set to `t` should do what you want.  check it out and let me know how it works for you.

**Comment by stevemolitor** [comment]
Yes `tsx-mode-css-force-highlighting` works perfectly thanks so much!
