### ISSUE TITLE
Generator names aren't highlighted

### ISSUE THREAD

**Issue by AdamNiederer** [orzechowskid/tsx-mode.el#16]
Repro:

```js
function* myGenerator() {}
```

`myGenerator` is rendered with `default-face`. Removing the asterisk causes it to be rendered with `tree-sitter-hl-face:function`, as expected.

Generator calls do appear to be highlighted correctly, however.

**Comment by orzechowskid** [comment]
I see this same behavior if I open a test Javscript file and enable `js-mode` major mode and `tree-sitter-hl-mode` minor mode:

```javascript
function myFn() {  // "myFn" fontified as tree-sitter-hl-face:function
}

function* myFn2() {  // "myFn2" fontified as default-face
}
```
I suspect that https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/master/queries/javascript/highlights.scm is missing some rules for generator functions.

**Comment by orzechowskid** [comment]
just opened https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/96 , FYI.
