### ISSUE TITLE
Indentation is broken, giving this error message: `tsi-indent-line: Symbol’s value as variable is void: node-at-point`

### ISSUE THREAD

**Issue by ckruse** [orzechowskid/tsx-mode.el#17]
Hey there,

this morning I updated treesitter and now indentation is broken: `tsi-indent-line: Symbol’s value as variable is void: node-at-point`

Stacktrace:

~~~
Debugger entered--Lisp error: (void-variable node-at-point)
  tsi-typescript--get-indent-for-current-line()
  tsi-indent-line(tsi-typescript--get-indent-for tsi-typescript--get-indent-for-current-line)
  tsi-typescript--indent-line()
  indent-according-to-mode()
  #<subr newline-and-indent>()
  apply(#<subr newline-and-indent> nil)
  newline-and-indent()
  funcall-interactively(newline-and-indent)
  command-execute(newline-and-indent)
~~~

- elisp-tree-sitter is at commit 5e1091658d625984c6c5756e3550c4d2eebd73a1
- tree-sitter-langs is at commit 0dd5e56e2f5646aa51ed0fc9eb869a8f7090228a
- tsx-mode is at commit 938bb7e21f409d1168270d5615fb24de32716908
- tsi is at commit 90410f6c0dbdfdd667ed3d10999a036c2a950e6d

Best regards,
  CK

**Comment by ckruse** [comment]
Hi @stevemolitor,

sigh. I am very sorry. I didn't remember deleting eln files before reporting the bug. After deleting my straight directory, the ELN cache and re-installing packages (just to be sure) everything works again.

I am very sorry for the noise :(

Best regards,
 CK

**Comment by stevemolitor** [comment]
No worries thanks for the reply @ckruse!
