### ISSUE TITLE
Self closing tag inserted in generic params

### ISSUE THREAD

**Issue by stevemolitor** [orzechowskid/tsx-mode.el#18]
With `tsx-mode-auto-tags` on, typing a `<` for a generic param will insert a self closing tag `</>`:

![](https://cdn.zappy.app/e8ae77dd7762d14093d3a9ba96414245.gif)

I hacked around it by checking `(tsx-mode--is-in-jsx-p)` in `tsx-mode-tsx-maybe-insert-self-closing-tag`:

```elisp
(defun tsx-mode-tsx-maybe-insert-self-closing-tag ()
  "When `tsx-mode-tsx-auto-tags' is non-nil, insert a self-closing element
instead of a plain '<' character (where it makes sense to)."
  (interactive)
  (if (and (tsx-mode--is-in-jsx-p)
           (or (bobp)
           (and tsx-mode-tsx-auto-tags
                (tsx-mode--tsx-self-closing-tag-at-point-p))))
      (progn
        (insert "</>")
        (backward-char 2))
    (insert "<")))
```

That seems to work, but I suspect the problem is `tsx-mode--tsx-self-closing-tag-at-point-p`: that should not be returning true here.

**Comment by orzechowskid** [comment]
> I suspect the problem is tsx-mode--tsx-self-closing-tag-at-point-p: that should not be returning true here.

yep, that turned out to be exactly the case.  I removed a short-circuit which seemed like a good idea when I wrote it and now generic types aren't treated as JSX (and a smoke test of JSX seemed to show it behaving as expected too).

let me know what you think!
