### ISSUE TITLE
Auto-close tags doesn't work reliably when opening an existing file

### ISSUE THREAD

**Issue by ckruse** [orzechowskid/tsx-mode.el#24]
Given a file `Settings.tsx` file with this context:

~~~tsx
const SevdeskSettings = () => {
  return (
    <fieldset>
      <legend>Foo</legend>
    </fieldset>
  );
};

export default SevdeskSettings;
~~~

Auto-closing tags doesn't work. E.g. placing the cursor behind the `</legend>` and opening a new tag just inserts the left angle bracket, but not, as expected, the `/>`. When I enter e.g. a `<span>` manually and now enter a `<`, it inserts a `/>` automatically.

I cleared the `eln-cache` directory before trying. With `tsx-mode-debug` set to `t` it gives me these messages in the `*Messages*` buffer when entering `<span><` after the `</legend>`:

~~~
old region: nil new region: nil
current CSS region: nil, in jsx:
You can run the command ‘eval-expression’ with M-:
current CSS region: nil, in jsx:
checking current named node jsx_text for self-closing tag support...
checking named node jsx_closing_element and anon node > for self-closing tag support...
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 59-87
fontifying 87-144
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 1-144
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 59-89
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 59-90
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 59-91
fontifying 91-148
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 1-148
fontifying 148-149
checking current named node jsx_text for self-closing tag support...
checking named node jsx_opening_element and anon node > for self-closing tag support...
regions: nil
old region: nil new region: nil [2 times]
current CSS region: nil, in jsx:
fontifying 59-95
fontifying 95-152
~~~

However, it *does* work as expected when I delete the fieldset and enter it manually again.

**Comment by ckruse** [comment]
OK, I could narrow it down. In `tsx-mode--tsx-self-closing-tag-at-point-p` you check if the last node is an opening tag or one of the special nodes `=>`, `(`, `?`, `:`, `[`, `,` or `=`. If it is none of that (no opening tag and none of the special chars) no self-closing tag will be inserted.

This fails when a parent node contains more than one element, e.g. in this scenario:

~~~jsx
<div>
  <span></span>
  <span></span>
</div>
~~~

There will be no `/>` inserted for the `div`. Then a `/>` gets inserted for the first span. But for the second span the last node type is a jsx_closing_element instead opening, and thus no `/>` gets inserted.

**Comment by ckruse** [comment]
Adding a `(eq last-named-node-type 'jsx_closing_element)` in the `(or …)` seems to do the trick.

**Comment by orzechowskid** [comment]
oh, good catch, thank you!
