### ISSUE TITLE
Indent does not function correctly until `tsi-mode` is reenabled

### ISSUE THREAD

**Issue by jacksonludwig** [orzechowskid/tsx-mode.el#30]
Hello, 

I noticed that when I use this plugin, the `tsi` plugin's functionality does not seem to work (e.g, indentation is incorrect) until I reenable `tsi-mode`.

This occurs with emacs `28.1.90`.

I can reproduce issue like this:

1. Open tsx file containing:
```typescript
const TestComp = (): ReactElement => {
  const { thing } = useContext(); <-- put cursor here

  return (
    <div>
    </div>
  );
};
```
2. Press enter
3. Observe cursor going to beginning of next line without being indented
4. Disable and reenable tsi mode
5. Do the same thing
6. Observe the cursor being indented correctly

Is there some load order of dependencies that is not being followed or something? Thanks.

**Comment by jacksonludwig** [comment]
I think it is necessary to make sure treesitter is loading before tsi.el, I will close for now unless I find this is not the case

**Comment by jacksonludwig** [comment]
Actually, any ideas on this? I can get `tsi.el` to function fine on it's own, but with `tsx-mode`, `tsi-typescript` must be reloaded to work.

**Comment by orzechowskid** [comment]
huh, interesting.  I do not see this behavior with the latest versions of tsi.el and tsx-mode.el .  could you tell me the version string contained in your copy of tsx-mode.el (or git revision of straight.el's version of your repo)?  does calling `straight-fetch-all` and `straight-rebuild-all` (then exiting and restarting emacs) fix the problem?

**Comment by jacksonludwig** [comment]
Hmm, it seems that with every updated I still have the same issue. I am able to reproduce it with this config:
```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'tree-sitter)
(straight-use-package 'tree-sitter-langs)
(require 'tree-sitter)
(require 'tree-sitter-langs)
(global-tree-sitter-mode)
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)

(straight-use-package '(tsi :type git :host github :repo "orzechowskid/tsi.el"))
(require 'tsi-typescript)
(require 'tsi-css)
(require 'tsi-json)

(straight-use-package 'coverlay)
(require 'coverlay)

(straight-use-package 'origami)
(require 'origami)

(straight-use-package 'company)
(require 'company)

(straight-use-package 'lsp-mode)
(setq lsp-headerline-breadcrumb-enable nil)
(setq lsp-enable-symbol-highlighting nil)
(setq lsp-signature-doc-lines 1)
(setq lsp-eldoc-enable-hover nil)
(setq lsp-on-type-formatting nil)
(setq lsp-enable-indentation nil)
(require 'lsp-mode)

(straight-use-package '(tsx-mode :type git :host github :repo "orzechowskid/tsx-mode.el"))
(require 'tsx-mode)
```

**Comment by orzechowskid** [comment]
oh!  I see what's happening.  disabling and enabling `tsi-typescript-mode` changes the value of `indent-line-function` to something that works for TS but not for CSS-in-JS, so it's not an issue with how dependencies are ordered.  it's that some updates were made to tsi.el and tsi-typescript.el but I never made the same updates to this library.

this should be a pretty simple fix.

**Comment by orzechowskid** [comment]
ok - please update tsi.el and edit your straight.el recipe to use branch `30/ts-indent` of this library, and let me know if that fixes your problem.

**Comment by jacksonludwig** [comment]
Thanks for checking this out.

It seems to me that indentation has improved, however I don't think the issue is totally fixed yet. Indentation looks good within jsx and within objects (e.g. `const thing = {...}`), but not quite within functions.

For example the following situation.
```typescript
const thing = () => { <-- cursor here
<-- cursor is not indented on hitting <CR>
}
```

**Comment by orzechowskid** [comment]
great.  I'll merge that branch and close this issue since behavior is improved now that tsx-mode.el is doing the right thing with its dependency, and I'll go ahead and raise an issue in that dependency to fix the new issue you're describing.

**Comment by stevemolitor** [comment]
Thanks for fixing this @orzechowskid. 

@jacksonludwig fwiw I noticed what you noticed about indentation within functions, but after doing a bit of a dance with `straight.el` to get it to re-pull and re-build both  the`tsi.el` and `tsx-mode.el` packages it works fine now:

```ts
const thing = () => { <-- cursor here
  <-- cursor is correctly indented on hitting <CR>
}
```

**Comment by jacksonludwig** [comment]
@stevemolitor yes you're right, I think I made the mistake of refetching when I needed to use pull-all instead. Thanks

my bad @orzechowskid, seems good now. Thanks for your help.
