### ISSUE TITLE
eslint LSP integration

### ISSUE THREAD

**Issue by jacksonludwig** [orzechowskid/tsx-mode.el#40]
I see that in the 29 branch of this plugin, the built-in eglot LSP client is used. I may be wrong but I think eglot on supports one server per buffer. Is there any way to integrate another lsp (commonly eslint) at this point?

Thanks.

**Comment by orzechowskid** [comment]
I think you're correct that eglot only supports one LSP server per buffer: https://github.com/joaotavora/eglot/issues/976 .  in the specific case of typescript plus eslint, the author of eglot suggests to use typescript-language-server as the LSP server and install the `flymake-eslint` emacs package to handle linting.  that of course does not support other features like inserting a comment to disable a rule, etc; if that's a dealbreaker for you then you can look into using emacs' own `tsx-ts-mode` plus `lsp-mode` plus [the css-in-js minor mode available here](https://github.com/orzechowskid/tree-sitter-css-in-js/tree/emacs29).

for what it's worth, [the comment here](https://github.com/joaotavora/eglot/issues/976#issuecomment-1355438003) seems to indicate that multiple concurrent LSP servers is on the eglot roadmap.

**Comment by jacksonludwig** [comment]
Okay got it. Thanks for the information.
