### ISSUE TITLE
Disabling eldoc-doc-buffer minibuffer popping up all the time

### ISSUE THREAD

**Issue by mariusk** [orzechowskid/tsx-mode.el#45]
Not sure if it's related to this mode or not, but I'm trying to disable whatever is causing an `eldoc-doc-buffer` minibuffer to show up all the time when this mode gets activated. I've tried numerous lsp related settings and eldoc related settings but without much luck. I also know that it is eldoc related because if I manually disable `eldoc-mode` in the buffer it stops appearing. I've also tried various hooks and what not to disable eldoc after a buffer activates `tsx-mode`, but not having much luck. Clues would be appreciated.

**Comment by orzechowskid** [comment]
as you discovered, disabling `eldoc-mode` will prevent its minibuffers from appearing at all.  if you never want to see any eldoc output at all then you should be able to register a hook at `eglot-managed-mode-hook` to disable `eldoc-mode` (which eglot, not `tsx-mode`, automatically enables for you):
```
(add-hook
  'eglot-managed-mode-hook
  (lambda ()
    (eldoc-mode -1)))
```
if you still want some eldoc output but wish to control when, or what, its minibuffer displays then see `eldoc-documentation-strategy`.  I think it's set to `eldoc-documentation-compose` out-out-of-the-box which runs all functions registered at `eldoc-documentation-functions` and writes all their output to the eldoc buffer.

hope this helps!

**Comment by mariusk** [comment]
Thank you, that works fine.
