### ISSUE TITLE
Auto-close current tag, or close current tag like rjsx-mode does

### ISSUE THREAD

**Issue by ckruse** [orzechowskid/tsx-mode.el#6]
Hi there,

first of all: thanks for your work!

Is it possible to automatically close the current tag like in web-mode, or, alternatively, mimic the behaviour of rjsx-mode with C-d?

Best regards,
 CK

**Comment by orzechowskid** [comment]
I tinkered with this a bit and I don't think it will be too hard to add support for some form of auto-closing tags.

typing `<` can insert `</>` (and place point immediately before the slash character) where it makes sense to do so. and typing `>' when point is immediately before the `/>` of a self-closing tag can remove that `/>` and replace it with `></foo>` (and place point between the opening and closing tags).

would that be sufficient?

**Comment by ckruse** [comment]
That sounds handy, yes! :-) Pretty similiar to how rsjx-mode handles it.

**Comment by orzechowskid** [comment]
ok!  there's a new `defcustom` named `tsx-mode-tsx-auto-tags` which when set to `t` should do what you want.  let me know how it works for you.  I don't personally use auto-closing tags so it's very likely I missed some cases where they would be useful.

**Comment by ckruse** [comment]
Great work, thank you very much! It works pretty good in my first experiments :-)

**Comment by ckruse** [comment]
There is a small problem: Tags with Dots get closed only with the part before the dot, e.g. `<InputGroupt.Text>` gets closed to `</InputGroup>`.

**Comment by orzechowskid** [comment]
oh, right!  I call `(thing-at-point 'word)` which of course will not return the `.` or anything after it.  I think a simple forward-search for non-whitespace characters will work better.

**Comment by ckruse** [comment]
Oh, another problem: when entering a `<` in a non-tsx context I get this error:

~~~
Debugger entered--Lisp error: (wrong-type-argument user-ptrp nil)
  tsc-node-byte-range(nil)
  tsc-node-position-range(nil)
  tsc--node-text(nil)
  tsc-node-text(nil)
  tsx-mode--tsx-self-closing-tag-at-point-p()
  tsx-mode-tsx-maybe-insert-self-closing-tag()
  funcall-interactively(tsx-mode-tsx-maybe-insert-self-closing-tag)
  command-execute(tsx-mode-tsx-maybe-insert-self-closing-tag)
~~~

**Comment by orzechowskid** [comment]
hm. can I get a small sample of TS code which demonstrates that problem?

**Comment by ckruse** [comment]
It looks like it fails for every generic. Trying to type `useFormikContext<` gives me the same error.

**Comment by orzechowskid** [comment]
I've pushed an update which should hopefully fix some more of these auto-closing-tag issues, including the two you mentioned.  it also adds some debug messages which will be emitted if the buffer-local variable `tsx-mode-debug` is `t`, so you can use that to help diagnose any more problems you have.

**Comment by orzechowskid** [comment]
great!
