### ISSUE TITLE
Highlighting is broken

### ISSUE THREAD

**Issue by ckruse** [orzechowskid/tsx-mode.el#8]
Hey there,

highlighting is broken for  comments. `// foo` in TSX code is marked as comment:

<img width="196" alt="Bildschirmfoto 2022-03-22 um 07 48 39" src="https://user-images.githubusercontent.com/175095/159423798-2787715e-65a9-4b48-8eb9-15055ee9ab81.png">

The `// foo` code is not a comment but a string.

I know that (most of?) syntax highlighting is done via TreeSitter, but I am unsure if you do some modifications. So sorry if I report it at the wrong place.

Best regards,
 CK

**Comment by orzechowskid** [comment]
hm, this seems to work correctly for me when I start with an empty buffer and create a component.  I suspect I'm font-locking the wrong part of a buffer when some event happens.

does this file include styled components?  if you create and then delete an empty styled-components region to trigger a font-lock (just `styled.div`` ` is sufficient), does the problem go away?

**Comment by ckruse** [comment]
Hm, I can't reproduce it anymore.

No, the file doesn't include styled components, we don't use them in this project.

I will try to reproduce it during the day, and when I can't I will close this bug, assuming that it was an outlier.

**Comment by ckruse** [comment]
I definitely still happens, but I was not yet able to create a minimal example reproducing it…

**Comment by orzechowskid** [comment]
if no CSS-in-JS strings are present in your source code then [syntax highlighting should be applied by `tree-sitter-hl-mode`](https://github.com/orzechowskid/tsx-mode.el/blob/7af1ba544374b6dc8a7963dca00cdc6d7b111c83/tsx-mode.el#L229) and not by any code I've written.  if you evaluate `(tree-sitter-hl--highlight-region (point-min) (point-max) nil)` in your buffer, is syntax highlighting applied correctly?

even if you can not create an example for us to reproduce the issue (and thank you for trying!), do you have a sense of the general circumstances which trigger it?  editing JSX?  adding comments?  something else?

**Comment by ckruse** [comment]
It didn't happen the last two days… I guess I misinterpreted something. I did notice some `//` rendered as comments where it was counter-intuitive but correct (I assumed a TSX context because it was located directly above the first tag, but this is of course a plain TS context). Sorry for the noise.
