### ISSUE TITLE
`comment-region` comments with `//`

### ISSUE THREAD

**Issue by ckruse** [orzechowskid/tsx-mode.el#9]
Hey there,

comment region comments with `//`. Within tsx code this is just a string. It should use `{/* */}` in a TSX context and `//` within a TS context.

Best regards,
 CK

**Comment by orzechowskid** [comment]
ah yes, good point.

I've pushed an update which should format comments as `{/* bracketed C-style comments */}` in TSX, `/* C-style comments */` in CSS-in-JS, and `// double-slash` comments in TS.  let me know how it works for you!

**Comment by ckruse** [comment]
Works pretty good, thanks a lot!
